#!/usr/bin/env python3
"""
Legal Disclaimers and Guardrails for MicroCFO
Ensures proper legal disclaimers are displayed and enforced
"""

from enum import Enum
from typing import Dict, Optional


class DisclaimerType(str, Enum):
    """Types of legal disclaimers"""
    GENERAL = "general"
    LEGAL_ADVICE = "legal_advice"
    FINANCIAL_ADVICE = "financial_advice"
    TAX_ADVICE = "tax_advice"
    NEGOTIATION = "negotiation"
    INVOICE_PROCESSING = "invoice_processing"
    SUBSIDY_APPLICATION = "subsidy_application"


class LegalDisclaimers:
    """
    Legal disclaimers for MicroCFO
    
    IMPORTANT: These disclaimers must be displayed prominently
    to users to ensure they understand the limitations of AI assistance.
    """
    
    # Main disclaimer - shown on every page
    MAIN_DISCLAIMER = """
    ⚠️ IMPORTANT DISCLAIMER
    
    Micro-CFO is an AI assistant, not a chartered accountant, lawyer, or financial advisor.
    
    All outputs, recommendations, and analyses provided by this system are for informational 
    purposes only and must be verified by a qualified professional before taking any action.
    
    Do not rely solely on AI-generated content for legal, financial, or tax decisions.
    Always consult with licensed professionals for advice specific to your situation.
    """
    
    # Specific disclaimers for different features
    DISCLAIMERS: Dict[DisclaimerType, str] = {
        DisclaimerType.GENERAL: """
        Micro-CFO is an AI assistant designed to help with financial operations.
        It is NOT a substitute for professional advice from chartered accountants,
        lawyers, or financial advisors. Always verify AI outputs with qualified professionals.
        """,
        
        DisclaimerType.LEGAL_ADVICE: """
        ⚖️ LEGAL DISCLAIMER
        
        The legal compliance information provided by Micro-CFO is for general informational
        purposes only and does not constitute legal advice. Laws and regulations change
        frequently, and their application can vary based on specific circumstances.
        
        You should:
        • Consult with a qualified lawyer or chartered accountant
        • Verify all legal interpretations with current legislation
        • Not rely solely on AI-generated legal analysis
        • Seek professional advice before making compliance decisions
        
        Micro-CFO and its creators assume no liability for decisions made based on
        AI-generated legal information.
        """,
        
        DisclaimerType.FINANCIAL_ADVICE: """
        💰 FINANCIAL DISCLAIMER
        
        Micro-CFO provides financial analysis and suggestions for informational purposes only.
        This is NOT financial advice and should not be treated as such.
        
        You should:
        • Consult with a certified financial advisor or chartered accountant
        • Verify all financial calculations and recommendations
        • Not make financial decisions based solely on AI outputs
        • Consider your specific financial situation and goals
        
        Past performance and AI predictions do not guarantee future results.
        """,
        
        DisclaimerType.TAX_ADVICE: """
        📊 TAX DISCLAIMER
        
        Tax information provided by Micro-CFO is for general guidance only and does not
        constitute tax advice. Tax laws are complex and subject to change.
        
        You should:
        • Consult with a qualified tax professional or chartered accountant
        • Verify all tax calculations and interpretations
        • File taxes only after professional review
        • Not rely on AI for tax planning or filing decisions
        
        Incorrect tax filings can result in penalties. Always seek professional tax advice.
        """,
        
        DisclaimerType.NEGOTIATION: """
        🤝 NEGOTIATION DISCLAIMER
        
        Negotiation emails generated by Micro-CFO are DRAFTS ONLY and must be reviewed
        and approved by you before sending.
        
        Important:
        • Micro-CFO will NEVER automatically send emails on your behalf
        • All generated content is a draft for your review
        • You are responsible for the content of any emails you send
        • Review and modify drafts to suit your specific situation
        • Consider legal and business implications before sending
        
        The AI cannot understand all nuances of your business relationships.
        Always review and customize generated content.
        """,
        
        DisclaimerType.INVOICE_PROCESSING: """
        📄 INVOICE PROCESSING DISCLAIMER
        
        Invoice data extracted by Micro-CFO using OCR and AI may contain errors.
        
        You should:
        • Verify all extracted data against original documents
        • Review amounts, dates, and vendor information carefully
        • Not approve invoices based solely on AI extraction
        • Implement proper approval workflows
        • Maintain original documents for audit purposes
        
        OCR accuracy can vary based on document quality. Always verify critical information.
        """,
        
        DisclaimerType.SUBSIDY_APPLICATION: """
        🎯 SUBSIDY APPLICATION DISCLAIMER
        
        Subsidy and scheme information provided by Micro-CFO may be incomplete or outdated.
        
        You should:
        • Verify eligibility criteria with official government sources
        • Check application deadlines and requirements
        • Consult with professionals familiar with subsidy applications
        • Review all application materials before submission
        • Not rely solely on AI for subsidy discovery
        
        Government schemes change frequently. Always verify with official sources.
        """
    }
    
    # Short disclaimers for UI elements
    SHORT_DISCLAIMERS: Dict[DisclaimerType, str] = {
        DisclaimerType.GENERAL: "⚠️ AI Assistant - Not a professional. Verify all outputs.",
        DisclaimerType.LEGAL_ADVICE: "⚖️ Not legal advice. Consult a lawyer or CA.",
        DisclaimerType.FINANCIAL_ADVICE: "💰 Not financial advice. Consult a financial advisor.",
        DisclaimerType.TAX_ADVICE: "📊 Not tax advice. Consult a tax professional.",
        DisclaimerType.NEGOTIATION: "🤝 Draft only. Review before sending.",
        DisclaimerType.INVOICE_PROCESSING: "📄 Verify extracted data against original.",
        DisclaimerType.SUBSIDY_APPLICATION: "🎯 Verify with official government sources."
    }
    
    @staticmethod
    def get_disclaimer(disclaimer_type: DisclaimerType, short: bool = False) -> str:
        """
        Get disclaimer text
        
        Args:
            disclaimer_type: Type of disclaimer
            short: Whether to return short version
            
        Returns:
            Disclaimer text
        """
        if short:
            return LegalDisclaimers.SHORT_DISCLAIMERS.get(
                disclaimer_type,
                LegalDisclaimers.SHORT_DISCLAIMERS[DisclaimerType.GENERAL]
            )
        else:
            return LegalDisclaimers.DISCLAIMERS.get(
                disclaimer_type,
                LegalDisclaimers.DISCLAIMERS[DisclaimerType.GENERAL]
            )
    
    @staticmethod
    def get_main_disclaimer() -> str:
        """Get main disclaimer text"""
        return LegalDisclaimers.MAIN_DISCLAIMER
    
    @staticmethod
    def format_for_api_response(disclaimer_type: DisclaimerType) -> Dict[str, str]:
        """
        Format disclaimer for API response
        
        Args:
            disclaimer_type: Type of disclaimer
            
        Returns:
            Dictionary with disclaimer information
        """
        return {
            "disclaimer": LegalDisclaimers.get_disclaimer(disclaimer_type, short=False),
            "disclaimer_short": LegalDisclaimers.get_disclaimer(disclaimer_type, short=True),
            "disclaimer_type": disclaimer_type.value,
            "must_acknowledge": True
        }


class Guardrails:
    """
    Guardrails for MicroCFO operations
    
    Enforces safety rules and prevents potentially harmful actions.
    """
    
    # Negotiator guardrails
    NEGOTIATOR_RULES = {
        "auto_send_enabled": False,  # NEVER auto-send emails
        "require_user_approval": True,  # Always require approval
        "draft_only": True,  # Only generate drafts
        "show_disclaimer": True,  # Always show disclaimer
    }
    
    # Invoice processing guardrails
    INVOICE_RULES = {
        "auto_approve_enabled": False,  # Never auto-approve invoices
        "require_verification": True,  # Always require verification
        "flag_high_amounts": True,  # Flag invoices over threshold
        "high_amount_threshold": 50000,  # ₹50,000 threshold
    }
    
    # Legal query guardrails
    LEGAL_RULES = {
        "provide_legal_advice": False,  # Never provide legal advice
        "show_disclaimer": True,  # Always show disclaimer
        "recommend_professional": True,  # Always recommend professional
    }
    
    @staticmethod
    def check_negotiator_action(action: str) -> tuple[bool, Optional[str]]:
        """
        Check if negotiator action is allowed
        
        Args:
            action: Action to check (e.g., "send_email", "generate_draft")
            
        Returns:
            Tuple of (allowed, reason_if_not_allowed)
        """
        if action == "send_email":
            return False, "Automatic email sending is disabled. Generate draft for user approval."
        
        if action == "generate_draft":
            return True, None
        
        return False, f"Unknown action: {action}"
    
    @staticmethod
    def check_invoice_approval(amount: float, auto_approve: bool = False) -> tuple[bool, Optional[str]]:
        """
        Check if invoice approval is allowed
        
        Args:
            amount: Invoice amount
            auto_approve: Whether auto-approval is requested
            
        Returns:
            Tuple of (allowed, reason_if_not_allowed)
        """
        if auto_approve:
            return False, "Automatic invoice approval is disabled. User approval required."
        
        if amount > Guardrails.INVOICE_RULES["high_amount_threshold"]:
            return False, f"Invoice amount (₹{amount:,.2f}) exceeds threshold. Additional verification required."
        
        return True, None
    
    @staticmethod
    def should_show_disclaimer(feature: str) -> bool:
        """
        Check if disclaimer should be shown for feature
        
        Args:
            feature: Feature name
            
        Returns:
            Whether disclaimer should be shown
        """
        # Always show disclaimers
        return True
    
    @staticmethod
    def get_professional_recommendation(feature: str) -> str:
        """
        Get recommendation for professional consultation
        
        Args:
            feature: Feature name
            
        Returns:
            Recommendation text
        """
        recommendations = {
            "legal": "Consult with a qualified lawyer or chartered accountant for legal advice.",
            "tax": "Consult with a tax professional or chartered accountant for tax advice.",
            "financial": "Consult with a certified financial advisor for financial advice.",
            "negotiation": "Review and customize the draft before sending. Consider legal implications.",
            "invoice": "Verify all extracted data and implement proper approval workflows.",
            "subsidy": "Verify eligibility and requirements with official government sources."
        }
        
        return recommendations.get(
            feature,
            "Consult with qualified professionals before making important decisions."
        )


# Convenience functions
def get_negotiator_disclaimer() -> Dict[str, str]:
    """Get negotiator disclaimer for API response"""
    return LegalDisclaimers.format_for_api_response(DisclaimerType.NEGOTIATION)


def get_legal_disclaimer() -> Dict[str, str]:
    """Get legal disclaimer for API response"""
    return LegalDisclaimers.format_for_api_response(DisclaimerType.LEGAL_ADVICE)


def get_invoice_disclaimer() -> Dict[str, str]:
    """Get invoice processing disclaimer for API response"""
    return LegalDisclaimers.format_for_api_response(DisclaimerType.INVOICE_PROCESSING)


def check_can_send_email() -> tuple[bool, str]:
    """Check if email can be sent automatically"""
    return Guardrails.check_negotiator_action("send_email")


if __name__ == "__main__":
    # Test disclaimers
    print("="*60)
    print("MAIN DISCLAIMER")
    print("="*60)
    print(LegalDisclaimers.get_main_disclaimer())
    
    print("\n" + "="*60)
    print("NEGOTIATION DISCLAIMER")
    print("="*60)
    print(LegalDisclaimers.get_disclaimer(DisclaimerType.NEGOTIATION))
    
    print("\n" + "="*60)
    print("GUARDRAILS TEST")
    print("="*60)
    
    # Test negotiator guardrails
    can_send, reason = Guardrails.check_negotiator_action("send_email")
    print(f"Can auto-send email: {can_send}")
    if not can_send:
        print(f"Reason: {reason}")
    
    can_draft, reason = Guardrails.check_negotiator_action("generate_draft")
    print(f"Can generate draft: {can_draft}")
    
    print("\n✅ Disclaimers and guardrails configured correctly")
