import React from 'react';
import { AlertCircle, CheckCircle, XCircle, Info } from 'lucide-react';
import { cn } from './ui/Button';

/**
 * Disclaimer Component
 * Displays legal disclaimers for AI-generated content
 */
const Disclaimer = ({ type = 'info', className = '', children }) => {
    const types = {
        info: {
            icon: Info,
            bg: 'bg-blue-50',
            border: 'border-blue-200',
            text: 'text-blue-800',
            iconColor: 'text-blue-600'
        },
        warning: {
            icon: AlertCircle,
            bg: 'bg-yellow-50',
            border: 'border-yellow-200',
            text: 'text-yellow-800',
            iconColor: 'text-yellow-600'
        },
        success: {
            icon: CheckCircle,
            bg: 'bg-green-50',
            border: 'border-green-200',
            text: 'text-green-800',
            iconColor: 'text-green-600'
        },
        error: {
            icon: XCircle,
            bg: 'bg-red-50',
            border: 'border-red-200',
            text: 'text-red-800',
            iconColor: 'text-red-600'
        }
    };

    const config = types[type];
    const Icon = config.icon;

    return (
        <div
            className={cn(
                'flex items-start gap-3 p-4 rounded-lg border',
                config.bg,
                config.border,
                config.text,
                className
            )}
        >
            <Icon className={cn('w-5 h-5 flex-shrink-0 mt-0.5', config.iconColor)} />
            <div className="text-sm">{children}</div>
        </div>
    );
};

/**
 * AI Disclaimer - Specific disclaimer for AI-generated content
 */
export const AIDisclaimer = () => (
    <Disclaimer type="warning" className="mt-4">
        <strong>AI-Generated Content:</strong> This response is generated by artificial intelligence and
        should be verified by a qualified Chartered Accountant before making critical financial decisions.
        MicroCFO does not provide professional advice.
    </Disclaimer>
);

/**
 * Legal Disclaimer - General legal disclaimer
 */
export const LegalDisclaimer = () => (
    <Disclaimer type="info">
        <strong>Legal Disclaimer:</strong> Information provided is for educational purposes only and
        does not constitute legal, tax, or financial advice. Consult with qualified professionals
        for specific guidance related to your situation.
    </Disclaimer>
);

export default Disclaimer;
