"""add business profiles and subsidy matches

Revision ID: 2ccceaa9b0b8
Revises: 001_add_encryption
Create Date: 2026-01-31 18:43:22.709658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.encryption

# revision identifiers, used by Alembic.
revision: str = '2ccceaa9b0b8'
down_revision: Union[str, Sequence[str], None] = '001_add_encryption'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('turnover_range', sa.String(length=50), nullable=True),
    sa.Column('gstin', src.encryption.EncryptedString(length=50), nullable=True),
    sa.Column('location_state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_business_owner', 'business_profiles', ['owner_id'], unique=False)
    op.create_index(op.f('ix_business_profiles_owner_id'), 'business_profiles', ['owner_id'], unique=False)
    op.create_table('subsidy_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsidy_matches_business_id'), 'subsidy_matches', ['business_id'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('invoices', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('image_url', src.encryption.EncryptedText(), nullable=True))
    op.add_column('invoices', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('compliance_status', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('audit_notes', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('invoices', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('idx_invoices_business_status', 'invoices', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'business_profiles', ['business_id'], ['id'], ondelete='SET NULL')
    op.alter_column('legal_queries', 'relevant_sections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('subsidy_applications', 'scheme_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.alter_column('workflow_states', 'context_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('workflow_states', 'history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_states', 'history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_states', 'context_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_number')
    op.alter_column('user_profiles', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('subsidy_applications', 'scheme_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('legal_queries', 'relevant_sections',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_index('idx_invoices_business_status', table_name='invoices')
    op.alter_column('invoices', 'extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('invoices', 'is_verified')
    op.drop_column('invoices', 'audit_notes')
    op.drop_column('invoices', 'compliance_status')
    op.drop_column('invoices', 'category')
    op.drop_column('invoices', 'image_url')
    op.drop_column('invoices', 'business_id')
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_subsidy_matches_business_id'), table_name='subsidy_matches')
    op.drop_table('subsidy_matches')
    op.drop_index(op.f('ix_business_profiles_owner_id'), table_name='business_profiles')
    op.drop_index('idx_business_owner', table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
