"""Add proactive intelligence tables

Revision ID: c00b0b57dc26
Revises: 375f898db4d4
Create Date: 2026-01-31 19:07:25.842715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00b0b57dc26'
down_revision: Union[str, Sequence[str], None] = '375f898db4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_change_monitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('law_type', sa.String(length=50), nullable=False),
    sa.Column('section_number', sa.String(length=100), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('hash_signature', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_signature')
    )
    op.create_index('idx_law_change_hash', 'law_change_monitors', ['hash_signature'], unique=False)
    op.create_index(op.f('ix_law_change_monitors_law_type'), 'law_change_monitors', ['law_type'], unique=False)
    op.create_table('user_law_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('law_type', sa.String(length=50), nullable=False),
    sa.Column('specific_sections', sa.JSON(), nullable=True),
    sa.Column('turnover_threshold_alert', sa.Boolean(), nullable=True),
    sa.Column('sector_specific_alert', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_law_sub_user_law', 'user_law_subscriptions', ['user_id', 'law_type'], unique=False)
    op.create_index(op.f('ix_user_law_subscriptions_user_id'), 'user_law_subscriptions', ['user_id'], unique=False)
    op.create_table('proactive_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('related_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('triggered_by_invoice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proactive_notifications_user_type', 'proactive_notifications', ['user_id', 'alert_type'], unique=False)
    op.create_index('idx_proactive_notifications_user_unread', 'proactive_notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_proactive_notifications_alert_type'), 'proactive_notifications', ['alert_type'], unique=False)
    op.create_index(op.f('ix_proactive_notifications_created_at'), 'proactive_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_proactive_notifications_is_read'), 'proactive_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_proactive_notifications_user_id'), 'proactive_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proactive_notifications_user_id'), table_name='proactive_notifications')
    op.drop_index(op.f('ix_proactive_notifications_is_read'), table_name='proactive_notifications')
    op.drop_index(op.f('ix_proactive_notifications_created_at'), table_name='proactive_notifications')
    op.drop_index(op.f('ix_proactive_notifications_alert_type'), table_name='proactive_notifications')
    op.drop_index('idx_proactive_notifications_user_unread', table_name='proactive_notifications')
    op.drop_index('idx_proactive_notifications_user_type', table_name='proactive_notifications')
    op.drop_table('proactive_notifications')
    op.drop_index(op.f('ix_user_law_subscriptions_user_id'), table_name='user_law_subscriptions')
    op.drop_index('idx_user_law_sub_user_law', table_name='user_law_subscriptions')
    op.drop_table('user_law_subscriptions')
    op.drop_index(op.f('ix_law_change_monitors_law_type'), table_name='law_change_monitors')
    op.drop_index('idx_law_change_hash', table_name='law_change_monitors')
    op.drop_table('law_change_monitors')
    # ### end Alembic commands ###
